import common from "./common.js";
export default {
  ...common,
  "menu.首页": "Home",
  "menu.account.logout": "Logout",
  "account.edit": "Edit account",
  "account.company.name": "Company name",
  "account.company.name.placeholder": "Please enter the company name",
  "account.save.button": "Save basic settings",
  "application.sir.phone.info":
    "Please enter the correct mobile number so that we can contact you",
  "application.company": "Company name",
  "station.id": "Charging station ID",
  "flow.edit.branch.more": "Add branch",
  "flow.edit.branch.delay.select.min": "Minute",
  "flow.edit.branch.generate.goods.map": "Select map",
  "flow.edit.branch.node.name": "Change name",
  "flow.page.title.chufajilu": "Trigger record",
  "flow.page.change.input": "Process name and description",
  "flow.type.cus": "Custom process",
  "flow.type.system": "System process",
  "hmi.login.account.warn":
    "The account number is your 11-digit mobile phone number",
  "hmi.login.version.alone": "Stand-alone",
  "hmi.login.version.clound": "Public cloud",
  "hmi.sys.net.operate.1": "Mobile",
  "hmi.sys.net.wifi.ip.show": "Display properties",
  "hmi.sys.senior.volumn": "Voice Volume",
  "hmi.sys.senior.model.2": "Counterbalance forklift truck",
  "hmi.sys.senior.model.3": "Porter",
  "hmi.menu.地图": "Map",
  "hmi.task.point.name": "Task point name",
  "home2d.menu.reset.map": "Reset map",
  "home2d.menu.control.map.envShowOrHide": "Show/Hide navigation map",
  "home2d.menu.control.map.carShowOrHide": "Show/hide all forklift",
  "home2d.menu.control.map.carShowOrHide.info":
    "Show/hide all forklift information",
  "home2d.menu.control.map.backgroundShowOrHide": "Show/Hide background",
  "home2d.menu.control.map.lockShowOrHide": "Show/Hide locks",
  "home2d.menu.control.map.axisShowOrHide": "Show/Hide axis",
  "home2d.menu.control.map.lineDirectionShowOrHide": "Show/Hide line direction",
  "home2d.menu.control.map.carDirectionShowOrHide": "Show/Hide heading",
  "home2d.menu.control.map.lineSpeedShowOrHide": "Show/Hide linear speed",
  "home2d.menu.control.map.lineDistanceShowOrHide": "Show/Hide lne distance",
  "home2d.menu.control.map.dotIdShowOrHide": "Show/Hide point ID",
  "home2d.menu.control.map.dotNameShowOrHide": "Show/Hide point names",
  "home2d.menu.followCar.map.cancel": "Cancel following",
  "home2d.map.save.map": "Submit map (Ctrl+S)",
  "home2d.createtask.executionCar": "Execution forklift",
  "home2d.createtask.name": "Task name",
  "home2d.createtask.compensate.end": "Ending point compensation",
  "home2d.createtask.point.floor.howMany.4": "Meter",
  "home2d.createtask.modal.modeLess.quick": "Quick task",
  "home2d.establish.env.deviation.setting.clockwise": "Rotation angle (angle)",
  "home2d.establish.env.saving": "Save map",
  "home2d.establish.env.addDot.fail": "Forklift location not obtained",
  "home2d.draw.withdraw.cancle": "Cancel recall (Ctrl+Y)",
  "home2d.createtask.modal.occupancy": "Release of occupation",
  "home2d.draw.shortcut.title1": "Shortcut key description",
  "home2d.draw.shortcut.a.select3":
    "The elements selected twice are not of the same type, please select again.",
  "home2d.draw.shortcut.a.fail":
    "Select two points at the same position, please select again",
  "home2d.draw.shortcut.ctrlY": "Ctrl+Y cancel recall",
  "home2d.draw.shortcut.ctrlV": "Ctrl+V paste",
  "home2d.draw.edit.title": "Property panel",
  "home2d.draw.point.edit.type.goods": "Cargo location",
  "home2d.draw.point.edit.type.goods.dot": "Cargo location",
  "home2d.draw.point.edit.tires": "Edit layer",
  "home2d.draw.point.edit.tires.id": "ID hidden",
  "home2d.draw.line.edit.rectilinear.direction.toEnd": "Towards the end point",
  "home2d.draw.line.edit.headstock.direction.toEnd": "Towards the end point",
  "home2d.draw.lock.edit.type": "Lock zone type",
  "home2d.draw.lock.edit.type.mark.name": "Region name",
  "home2d.agv.name": "Unmanned forklift",
  "home2d.point.color": "Color of points",
  "home2d.point.good.empty": "Cargo location - out of stock status",
  "home2d.point.good.in.stock": "Cargo location - In stock status",
  "home2d.quick.ui.word.recall.cancel": "Cancel recall",
  "home2d.dot.already.exist": "Points have been generated at this location",
  "mapList.table.ifDefault": "Whether to use the default map",
  "mapList.modal.forkUp.extra":
    "Configure the additional lifting height of the fork when picking up goods. If not filled in, the default is 0.1.",
  "mapList.mapdata.add.alert1": "Map name",
  "menu.admin.sub-page": "Secondary management page",
  "menu.信息": "Map",
  "scence.didiu.chanxian": "Ground pile-Production line",
  "service.create": "New service",
  "service.edit.long": "Editing services",
  "service.name": "Instance name",
  "service.release.error": "Failed to release the service resource",
  "service.url": "Service access address",
  "service.visit": "Service access address",
  "simulation.name": "Simulation name",
  "simulation.duration.info":
    "The default duration is 1 minute; The shortest duration is 1 minute",
  "slamMap.applyforklift.all": "Select all forklift",
  "slamMap.build.update.slam.error.info":
    "Failed toupdate the forklift map, please try again",
  "slamMap.build.forklift.position.error.info":
    "Failed toupdate the forklift map, please try again",
  "slamMap.build.create.slam.error.info":
    "Failed to enter mapping mode, please try again",
  "forklift.model.update.3d.fork": "3D fork model",
  "forklift.status.OFFLINE": "Offline",
  "work.edit.arrived": "Near end event",
  "work.export.name": "Taskname",
  "work.export.mapName": "Map name",
  "work.data.name": "Map name",
  "work.data.map": "Map",
  "work.workSTatus.5": "Cancel execution",
  "work.taskType.7": "Custom tasks",
  "work.eventList.startArriveNotify": "Task start point notification reached",
  "alarm.type": "Alarm type ",
  "alarm.device.name": "Device name",
  "car.warnning.10023":
    "Picking up, requesting out of stock but stock available",
  "car.warnning.10024": "Exit, request out of stock but stock available",
  "component.globalHeader.help": "Using documents",
  "component.globalHeader.event": "To do list",
  "component.globalHeader.event.empty": "You have completed all to-dos",
  "pager.operate.online": "Online",
  "pager.operate.offline": "Offline",
  "pager.detail.params.name": "Parameter name",
  "pager.detail.buttons.setting.name": "Button name",
  "universal.name.screen.out": "Exit full screen",
  "universal.system.name": "System name",
  // "": "",
  // "": "",
  // "": "",
  // "": "",
  // "": "",
  // "": "",
  // "": "",
  // "": "",
  // "": "",
  // "": "",
  // "": "",
  // "": "",
  // "": "",
  // "": "",
  // "": "",
  // "": "",
  // "": "",
  // "": "",
  // "": "",
  // "": "",
  // "": "",
  // "": "",
  // "": "",
  // "": "",
  // "": "",
  // "": "",
  // "": "",
  // "": "",
  // "": "",
  // "": "",
  // "": "",
  // "": "",
  // "": "",
  // "": "",
  // "": "",
  // "": "",
  // "": "",
  // "": "",
  // "": "",
  // "": "",
  // "": "",
  // "": "",
  // "": "",
  // "": "",
  // "": "",
  // "": "",
  // "": "",
  // "": "",
  // "": "",
  // "": "",
  // "": "",
  // "": "",
  // "": "",
  // "": "",
  // "": "",
  // "": "",
  // "": "",
  // "": "",
  // "": "",
  // "": "",
  // "": "",
  // "": "",
  // "": "",
  // "": "",
  // "": "",
  // "": "",
  // "": "",
  // "": "",
  // "": "",
  // "": "",
  // "": "",
  // "": "",
  // "": "",
  // "": "",
  // "": "",
  // "": "",
  // "": "",
};
