import common from "./common.js";
export default {
  ...common,
  "account.password.placeholder": "アカウントのパスワードを入力してください",
  "account.username.call": "呼び名／呼称",
  "account.delete": "削除",
  "account.your.username": "お名前",
  "account.your.avator.change": "アイコンの変更",
  "account.security.password.modify.success":
    "変更は成功しました。ページが終了します。再度ログインしてください。",
  "application.passed": "合格した",
  "application.name": "呼び名／呼称",
  "application.pass.ask": "この申請を承認してもよろしいですか",
  "application.pass": "合格",
  "application.refuse.ask": "この申請を拒否してもよろしいですか",
  "application.apply.error.info":
    "{name}ユーザー、こんにちは！申請が承認されなかったことをお詫び申し上げます。",
  "application.pass.text": "[合格]の返信テンプレート",
  "application.code.on.the.way":
    "SMS 認証コードが送信されました。しばらくお待ちください。",
  "application.code.fail":
    "認証コードを取得できませんでした。もう一度お試しください。",
  "application.code.retry": "認証コードを再送します",
  "application.title": "星空™AIクラウドプラットフォームのトライアルを申し込む ",
  "application.sir.name": "お名前",
  "application.sir.job": "あなたの役職",
  "application.sir.job.placeholder": "役職を入力してください",
  "application.sir.phone.info":
    "ご連絡が取れるように正しい携帯電話番号を入力してください",
  "application.go.login": "ログイン",
  "station.delete.ask": "この充電パイルを削除してもよろしいですか?",
  "station.delete.doing": "充電パイルを削除しています……",
  "station.invocation.ask": "この充電パイルを有効にしてもよろしいですか?",
  "station.invocation.doing": "充電パイルを有効にしています……",
  "station.disable.ask": "この充電パイルを無効にしてもよろしいですか?",
  "station.disable.doing": "充電ステーションが無効になっています……",
  "station.id": "充電パイルID",
  "station.map.name": "地図名",
  "station.release": "解放された",
  "flow.quxiaochufa": "この触発をキャンセルしてもよろしいですか?",
  "flow.liucheng.rizhi": "ログ",
  "flow.edit.branch.charge": "充電",
  "flow.edit.branch.charge.point": "充電ポイント",
  "flow.edit.branch.fork": "パレットフォーク",
  "flow.edit.branch.fork.height": "パレットフォーク高さ",
  "flow.edit.branch.fork.height.tell": "パレットフォーク高さを入力してください",
  "flow.edit.branch.agvMove.target.tell":
    "ターゲットポイントを入力してください",
  "flow.edit.branch.agvFetch.name": "車両",
  "flow.edit.branch.agvFetch.select": "車両を選択する",
  "flow.edit.branch.agvPickUp": "商品を取る",
  "flow.edit.branch.agvPickUp.point": "集荷場",
  "flow.edit.branch.agvPickUp.point.tell": "集荷場を入力してください",
  "flow.edit.branch.release.good.position": "荷降ろしポイント",
  "flow.edit.branch.release.good.position.tell":
    "荷降ろしポイントを入力してください",
  "flow.edit.branch.agv.tran": "運搬",
  "flow.edit.branch.agv.tran.start": "作業開始点",
  "flow.edit.branch.agv.tran.end": "作業終了点",
  "flow.edit.branch.api": "API リクエストの送信",
  "flow.edit.branch.delay.in": "まで",
  "flow.edit.branch.inject.to": "まで",
  "flow.edit.branch.delay.option.2": "ランダムな遅延",
  "flow.edit.branch.generate.goods": "材料の作成",
  "flow.edit.branch.generate.goods.map": "地図の選択",
  "flow.edit.branch.transport.goods": "転送材料",
  "flow.edit.branch.transport.goods.ifdis":
    "転送完了後、材料の消失を許可しますか",
  "flow.edit.branch.transport.goods.item": "材料",
  "flow.edit.branch.webhook": "webhook触発",
  "flow.edit.branch.webhook.param.type": "タイプ",
  "flow.type": "タイプ",
  "flow.edit.branch.webhook.type.number": "数値",
  "flow.edit.branch.webhook.value.base": "参考値",
  "flow.edit.branch.webhook.params.value": "参考値",
  "flow.edit.branch.webhook.param.error":
    "形式の検証に失敗しました。修正してください",
  "flow.edit.branch.webhook.request.way.info": "リクエストを受け取るURL",
  "flow.edit.branch.webhook.next": "次へ",
  "flow.edit.branch.webhook.back": "戻る",
  "flow.edit.branch.webhook.params.from.info":
    "システムは、以下のパラメータリストに基づいてリクエストからデータを取得します",
  "flow.edit.branch.webhook.modify": "修正",
  "flow.edit.branch.webhook.configed": "設定済み",
  "flow.edit.branch.simulate": "シミュレーショントリガー",
  "flow.edit.branch.simulate.loop": "循環",
  "flow.edit.branch.inject.loop": "循環",
  "flow.edit.branch.simulate.once": "1回循環",
  "flow.edit.branch.inject.one": "1回循環",
  "flow.edit.branch.node.delete": "削除",
  "flow.edit.branch.node.delete.sure": "削除の確認",
  "flow.edit.branch.node.delete.ask": "このノードを削除してもよろしいですか?",
  "flow.update.config.unfinished": "まだ構成されていないノードが存在します。",
  "flow.update.doing": "プロセスを公開しています……",
  "flow.update.success": "正常に公開されました。ページはすぐに更新されます……",
  "flow.page.title.chufajilu": "トリガーレコード",
  "flow.page.update.button": "更新リリース",
  "flow.sure.button": "確定",
  "flow.record.task.triggerTime": "トリガー時間",
  "flow.do.trigger": "即時トリガー",
  "flow.trigger.fangzhen": "シミュレーション専用トリガー",
  "flow.trigger.iot": "IoTデバイストリガー",
  "flow.update.time": "変更時間",
  "flow.select.status.placehold": "ステータスを選択してください",
  "flow.ask.cancel.all": "すべてキャンセルしてもよろしいですか?",
  "flow.doing.cancel.all": "すべてキャンセル中",
  "flow.detail.node.enter.time": "アクセス時間",
  "flow.detail.node.leave.time": "退出時間",
  "flow.detail.node.params.value": "値",
  "flow.detail.node.params": "このノードによって維持されるデータ",
  "flow.status.CREATED": "作成",
  "flow.status.ALLOCATED": "配布",
  "flow.status.FAILURE": "失敗",
  "flow.status.SOURCE_MOVING": "出発点に向かって進む",
  "flow.status.LOADED": "ロード済み",
  "flow.status.SOURCE_LEAVING": "もうすぐ出発点を離れる",
  "flow.status.TARGET_MOVING": "終点に向かって進む",
  "flow.status.TARGET_WILL_BE_ARRIVED": "まもなく終点に到着",
  "flow.status.TARGET_LEAVING": "もうすぐ終点を離れる",
  "flow.iot.device.type.callbox": "呼び出し器",
  "flow.iot.device.type.callbox.button": "トリガーボタン",
  "flow.iot.device.type.callbox.button.do": "ボタントリガー",
  "flow.iot.device.type.callbox.type": "呼び出し器の種類",
  "flow.api.request": "リクエストパラメータリスト",
  "flow.api.fail":
    "リクエストがタイムアウトした場合またはリクエストが失敗した場合",
  "flow.edit.branch.inject.max": "最大サイクル",
  "flow.edit.branch.inject.once": "即時に1回実行",
  "hmi.lead.step.2": "固定地点にルートを描きます",
  "hmi.login.account.warn": "アカウントは11桁の携帯番号です",
  "hmi.login.sureIn": "ログイン",
  "hmi.login.back": "戻る",
  "hmi.login.version.clound": "パブリッククラウド",
  "hmi.info.task.type": "タスクのタイプ",
  "hmi.info.car.angle": "ハンドル角度",
  "hmi.info.car.speed": "ハンドル速度",
  "hmi.info.more": "もっと／もっと見る",
  "hmi.map.select.scence.warn": "最初にシーンを選択してください",
  "hmi.sys.radar": "ナビゲーションレーダーIP",
  "hmi.sys.wireless": "無線IP",
  "hmi.sys.net.hot.open.ask": "ホットスポットを有効にしてもよろしいですか?",
  "hmi.sys.net.hot.open.doing": "ホットスポットを有効にしています...",
  "hmi.sys.net.ask": "端末モードを切り替えてもよろしいですか？",
  "hmi.sys.net.wifi.config.fail": "WIFI設定に失敗しました",
  "hmi.sys.net.operate.0": "中国聯通（チャイナユニコム）",
  "hmi.sys.net.operate.1": "中国移動（チャイナモバイル）",
  "hmi.sys.net.operate.2": "中国聯通（チャイナテレコム）",
  "hmi.sys.net.wifi.ip.dns": "DNSサーバーのアドレス",
  "hmi.sys.net.wifi.connecting": "接続",
  "hmi.sys.net.wifi.signal": "信号強度",
  "hmi.sys.net.wifi.ip.hide": "非表示のプロパティ",
  "hmi.sys.senior.setting": "構成を変更しています……",
  "hmi.sys.senior.open": "オーペン",
  "hmi.sys.senior.placeholder": "新しい値を入力します",
  "hmi.sys.senior.volumn": "音声ボリューム",
  "hmi.sys.senior.volumn.success": "音声ボリュームの変更に成功しました",
  "hmi.sys.senior.volumn.error": "音声ボリュームの変更に失敗しました",
  "hmi.sys.senior.model.3": "運搬車",
  "hmi.menu.任务": "タスク",
  "hmi.task.cancel.success": "キャンセルに成功しました",
  "hmi.task.refresh": "データを更新します",
  "hmi.car.relocation.handle.fail":
    "位置の再配置に失敗しました。再試行してください",
  "hmi.log.name": "名前",
  "home2d.menu.zoom.enlarge": "1 レベル拡大します",
  "home2d.menu.zoom.narrow": "1 レベル縮小します",
  "home2d.menu.fullscreen.map": "全画面表示",
  "home2d.menu.control.map.axisShowOrHide": "軸（or 座標軸）の表示/非表示",
  "home2d.menu.followCar.map": "車両を追跡する",
  "home2d.menu.searchDot.map.clear": "クリア",
  "home2d.map.warn.title": "ご注意",
  "home2d.vehicle.mode": "パターン",
  "home2d.vehicle.power": "電量",
  "home2d.createtask.type": "タイプ",
  "home2d.draw.point.edit.type": "タイプ",
  "home2d.createtask.executionCar": "実行車両",
  "home2d.createtask.weight": "重量",
  "home2d.createtask.compensate.start": "原点補正",
  "home2d.createtask.compensate.end": "エンドポイント補正",
  "home2d.createtask.point.floor": "第一層，高さ0メートル",
  "home2d.createtask.point.floor.howMany.2": "層",
  "home2d.createtask.modal.name": "名前",
  "home2d.draw.point.edit.name": "名前",
  "home2d.createtask.modal.end": "終点に設定",
  "home2d.createtask.modal.avoid.set": "待避点に設定",
  "home2d.establish.env.addDot.goods": "貨物位置を追加します",
  "home2d.establish.env.closing": "ナビゲーションマップを閉じています",
  "home2d.establish.env.creating": "ナビゲーションマップを新規作成中",
  "home2d.establish.env.saving": "地図を保存中……",
  "home2d.establish.env.fetch": "ナビゲーションマップを取得中",
  "home2d.draw.smart.base": "シングルポイントオートアラインメントを有効にする",
  "home2d.draw.withdraw": "取り消し（Ctrl + Z）",
  "home2d.draw.withdraw.cancle": "取消",
  "home2d.draw.save": "保存",
  "home2d.draw.save.title": "この地図データを保存して送信してもよろしいですか?",
  "home2d.draw.save.line.delete": "ラインに関連付けられていない点を削除します",
  "home2d.createtask.modal.radarCompensation": "ポイント補償",
  "home2d.task.drawer.come.compensate": "ポイント補償",
  "home2d.draw.shortcut.a.select1": "1を選択しました",
  "home2d.draw.shortcut.c.up": "上",
  "home2d.draw.shortcut.c.dirction": "アレ方向",
  "home2d.draw.shortcut.c.delete": "このデータ列を削除してもよろしいですか?",
  "home2d.draw.shortcut.ctrlMove": "Ctrl+マウスの左クリック　要素を選択する",
  "home2d.draw.shortcut.ctrlZ": "Ctrl+Z　取消す",
  "home2d.draw.shortcut.ctrlY": "Ctrl+Y　取消す",
  "home2d.draw.shortcut.ctrlS": "Ctrl+S　地図を提出する",
  "home2d.draw.point.edit.coord": "座標",
  "home2d.draw.point.edit.type.goods": "荷置き場",
  "home2d.draw.point.edit.type.goods.dot": "貨物置き場",
  "home2d.draw.point.edit.type.normal": "通常",
  "home2d.draw.point.edit.type.normal.dot": "通常ポイント（通常点）",
  "home2d.draw.point.edit.type.charge": "充電",
  "home2d.task.drawer.charge": "充電",
  "home2d.draw.point.edit.name.placeholder": "ポイント名を入力してください",
  "home2d.draw.point.edit.forkheight": "フォークの荷受け上げ高さ",
  "home2d.draw.point.edit.tires.failPass":
    "検証に失敗しました。確認してください",
  "home2d.draw.point.edit.tires.forkheight.placeholder":
    "フォークの荷受け上げ高さを入力ください",
  "home2d.draw.line.edit.headstock.direction.alwayToHead":
    "常に車頭の方向を向いています",
  "home2d.draw.line.edit.headstock.direction.headP": "車頭方向を優先",
  "home2d.draw.line.edit.ifLock.yes": "ロック",
  "home2d.draw.line.edit.acceleration": "加速度",
  "home2d.draw.line.edit.reverseSpeed": "逆速度",
  "home2d.draw.line.edit.reverseAcceleration": "逆加速度",
  "home2d.draw.line.edit.radius": "半径",
  "home2d.draw.lock.edit.type.mark": "識別エリア",
  "home2d.draw.lock.edit.type.mark.name": "エリア名",
  "home2d.draw.lock.edit.type.mark.placeholder": "エリア名を入力してください",
  "home2d.agv.diriction": "車両方向",
  "home2d.update.area.fail":
    "エリア情報の更新に失敗しました。再試行してください！",
  "home2d.area": "エリア",
  "home2d.point.good.empty": "貨物置き場-出荷ステータスなし",
  "home2d.point.good.in.stock": "貨物置き場-在庫ステータス",
  "home2d.point.control": "制御点",
  "home2d.point.avoid": "回避点",
  "home2d.line.dirction.point.one": "線の始点または終点に向かう",
  "home2d.map.name": "地図名",
  "home2d.quick.ui.word.recall": "取消す",
  "home2d.quick.ui.word.recall.cancel": "取消す",
  "home2d.quick.ui.word.copy": "コピー",
  "home2d.task.drawer.capacity": "倉庫の容量",
  "home2d.task.drawer.come.release": "その点に荷物を置く",
  "home2d.task.drawer.call": "呼び出し",
  "home2d.task.drawer.align": "位置合わせ",
  "home2d.grid.size": "グリッドサイズ",
  "home2d.open.ask.storage.ok": "はい、キャッシュデータをロードします",
  "home2d.save.area.name.cannot.empty": "エリアタイプ名は必須です！",
  "home2d.save.area.type.cannot.empty":
    "名前が[{name}]のエリアは、エリアタイプが選択されていません！！",
  "mapList.table.name": "名前",
  "mapList.table.ifDefault": "デフォルトのマップを使用するかどうか",
  "mapList.table.plan": "計画／プラン",
  "mapList.modal.slamMapId.placeholder":
    "この地図の背景として使用できるナビゲーションマップを選択してください",
  "mapList.mapdata.delete.alert": "このマップを削除してもよろしいですか?",
  "mapList.mapdata.fetching.mapdata.alert": "地図データを要求しています……",
  "menu.application": "申請管理",
  "menu.book": "組織アドレス帳",
  "menu.organize.book": "組織アドレス帳",
  "menu.camera": "現場画面",
  "menu.deviceSaasChargeStation": "充電パイル",
  "menu.scence.device.deviceSaasChargeStation": "充電パイル",
  "menu.deviceSaasPager": "呼出し器",
  "menu.scence.device.deviceSaasPager": "呼出し器",
  "menu.flow.logic": "ロジックリスト",
  "menu.flow.red": "ロジックリスト",
  "menu.admin.sub-page": "セカンダリ管理ページ",
  "menu.login": "ログイン",
  "menu.form.advanced-form": "高度なフォーム",
  "menu.profile.advanced": "高度な詳細ページ",
  "menu.exception": "異常ページ",
  "menu.account.center": "個人センター",
  "menu.account.logout": "ログアウト",
  "menu.系统.日志记录": "ロギング",
  "menu.log.s": "ログ",
  "scence.didiu.huojia": "地積み-棚",
  "scence.huojia.chanxian": "棚-生産ライン",
  "scence.kuoloucengbanyun": "フロア間の移動",
  "scence.name": "名前",
  "scence.cover.change": "カバーを変更します",
  "scence.name.update": "名前を変更します",
  "scence.operate.ask": "{inused}「{title}」シーンを本当に必要ですか?",
  "scence.delete.ask": "「{name}」シーンを削除してもよろしいですか?",
  "scence.cover": "カバー",
  "scence.delete": "シーンを削除します",
  "service.instance.destory.ask":
    "このインスタンスを削除（or 破壊）してよろしいですか？",
  "service.fee": "請求モデル",
  "simulation.if.finished": "終了済みかどうか",
  "simulation.is.finished": "終了しました",
  "simulation.delete": "削除",
  "slamMap.table.apply": "適用",
  "slamMap.applyCar": "適用",
  "slamMap.fetching.alert": "車両データを取得しています",
  "slamMap.fetching": "地図データを要求しています……",
  "slamMap.fetching.car.alert":
    "ナビゲーション地図データがありませんので、まず図を建てください",
  "slamMap.applyCar.title": "車の設定に地図を適用します",
  "slamMap.applyCar.all": "すべての車を選択します",
  "slamMap.edit.name": "名前",
  "slamMap.ADD.fail.alert": "新しいナビゲーションマップの作成に失敗しました",
  "slamMap.edit.file.upload": "ナビゲーションファイル",
  "slamMap.build.create.slam.error.info":
    "マッピングモードに正常に入れませんでした。再試行してください",
  "vehicle.update.data.success": "車両情報の更新に成功しました！",
  "vehicle.reseting.data": "リセット中",
  "vehicle.upload.data": "インポート",
  "vehicle.table.name": "名前",
  "vehicle.table.lowline": "低電圧閾値",
  "vehicle.table.highline": "高電圧閾値",
  "vehicle.table.chargingPile": "充電パイル",
  "vehicle.warn.title": "ご注意",
  "vehicle.detail.deviation.right": "エッジビット右オフセット",
  "vehicle.detail.charge": "充電",
  "vehicle.detail.autoChargeMode": "自動充電方法",
  "vehicle.detail.chargingPile.name": "充電パイル名",
  "vehicle.detail.chargingPile.placeholder": "充電パイル名を入力してください",
  "vehicle.detail.waitTime.placeholder":
    "アイドル時待ち時間/秒を入力してください",
  "vehicle.detail.powerlimit": "スケジューリング最低電力閾値（%）",
  "vehicle.detail.lowDoor": "低電圧閾値",
  "vehicle.detail.lowDoor.placeholder": "低電圧閾値を入力してください",
  "vehicle.detail.highDoor.placeholder": "高電圧閾値を入力してください",
  "vehicle.detail.highDoor": "高電圧閾値",
  "vehicle.detail.moveOnce.placeholder": "シングル最大変位量を入力してください",
  "vehicle.detail.ifIllegalCompensation": "不当補償",
  "vehicle.detail.ifIllegalCompensation.placeholder":
    "不当補償が必要かどうかを選択してください",
  "vehicle.detail.reset.dot.extra":
    "複数のリセットポイントを設定する場合は、英文カンマで区切ってください。例：DMQ 1、DMQ 2",
  "vehicle.model": "車両モデル",
  "vehicle.release": "解放",
  "vehicle.release.doing": "解放中",
  "vehicle.release.success": "解放成功",
  "vehicle.if.real": "シミュレーションカーですか",
  "vehicle.restore.success": "車両の復元に成功しました！",
  "vehicle.batch.restore": "一括復元",
  "vehicle.batch.update.warn.empty":
    "まず「一括変更」が必要な車両を選択してください",
  "vehicle.batch.update.doing": "「一括変更」中……",
  "vehicle.batch.restore.warn.empty": "まず「復元」する車両を選んでください",
  "vehicle.batch.restore.warn.condition":
    "「一時停止」状態の車両のみ復元可能ですので、再度選択してください",
  "vehicle.batch.update.fail": "「一括変更」に失敗しました……",
  "vehicle.batch.update.fail.some":
    "「一括変更」に失敗したのは、次のとおりです。",
  "vehicle.batch.update.success": "「一括変更」に成功しました",
  "vehicle.batch.pause.fail.some":
    "「一括一時停止」に失敗したのは、次のとおりです。",
  "vehicle.batch.restore.fail": "一括復元に失敗しました……",
  "vehicle.batch.restore.fail.some": "一括復元に失敗したのは、次のとおりです。",
  "vehicle.batch.restore.success": "一括復元に成功しました",
  "vehicle.batch.restore.ask":
    "選択した{number}バーのデータを「一括復元」しますか？",
  "vehicle.batch.pause.ask":
    "選択した{number}バーのデータを「一括一時停止」しますか？",
  "vehicle.batch.update.ask":
    "選択した{number}バーのデータを「一括変更」しますか？",
  "vehicle.status.ALARM": "警報",
  "vehicle.status.EXCEPTION": "異常",
  "work.table.name": "名前",
  "work.table.status.LOAD": "ピッキング開始",
  "work.table.status.ERROR": "タスク異常",
  "work.warn.title": "ご注意",
  "work.edit.eventListen": "イベントリスナー",
  "work.edit.arriveEvent.placeholder": "開始イベントを選択してください",
  "work.edit.pickupEvent.placeholder":
    "ピッキング中のノードイベントを選択してください",
  "work.edit.pickFinish.placeholder":
    "ロード完了ノードイベントを選択してください",
  "work.edit.arrived": "終了イベント",
  "work.export.number.alert": "エクスポートする数量を入力してください！",
  "work.export.mapName": "地図名",
  "work.data.name": "地図名",
  "work.export.car": "実行車両",
  "work.data.excuteCar": "実行車両",
  "work.data.eCar": "車両",
  "work.detail.orderId": "運送伝票シリアルナンバー",
  "work.detail.type": "タイプ",
  "work.detail.end": "実行終了時間",
  "work.detail.startPointEx": "起点補償",
  "work.detail.endPointEx": "終点補償",
  "work.detail.weight": "重量",
  "work.detail.process": "実行進捗",
  "work.workSTatus.4": "実行失敗/異常",
  "work.workSTatus.5": "実行キャンセル",
  "work.taskType.4": "荷卸しタスク",
  "work.taskType.6": "充電タスク",
  "work.actionList.1": "フォーク",
  "work.actionList.3": "トラクション",
  "work.processType.1": "出発点点に到達していません",
  "work.processType.6": "開始アクションがすべて完了しました",
  "work.processType.7": "まもなく終点に到着",
  "work.eventList.startLeaveNotify": "タスク開始点から離れましたことの通知",
  "work.eventList.endArriveNotify": "タスクの終了地点に到着した通知",
  "work.eventList.endLeaveNotify": "タスクの終了地点に離れた通知",
  "work.export.task": "タスク",
  "alarm.status": "アラームステータス",
  "car.warnning.10000":
    "サイドゴムストリップがトリガーされました。周囲の障害物を確認してください。緊急停止ボタンを押して引き上げて復旧できます。",
  "car.warnning.10001":
    "左の叉先光電がトリガーされました。周囲に障害物があるかどうかを確認してください。",
  "car.warnning.10002":
    "右の叉先光電がトリガーされました。周囲に障害物があるかどうかを確認してください。",
  "car.warnning.10003":
    "左脚光電がトリガーされました。周囲に障害物があるかどうかを確認してください。",
  "car.warnning.10004":
    "右脚光電がトリガーされました。周囲に障害物があるかどうかを確認してください。",
  "car.warnning.10005":
    "左側の安全レーダー駐車エリアで障害物が検出されました。周囲に障害物が存在するか確認してください。",
  "car.warnning.10006": "左側の安全レーダー警告2エリアがトリガーされました",
  "car.warnning.10007": "左側の安全レーダー警告1エリアがトリガーされました",
  "car.warnning.10008":
    "右側の安全レーダー駐車エリアで障害物が検出されました。周囲に障害物が存在するか確認してください。",
  "car.warnning.10009": "右側の安全レーダー警告2エリアがトリガーされました",
  "car.warnning.10010": "右側の安全レーダー警告1エリアがトリガーされました",
  "car.warnning.10011":
    "3号の安全レーダー駐車エリアで障害物が検出されました。周囲に障害物が存在するか確認してください。",
  "car.warnning.10012": "3号の安全レーダー警告2エリアがトリガーされました",
  "car.warnning.10013": "3号の安全レーダー警告1エリアがトリガーされました",
  "car.warnning.10014":
    "4号の安全レーダー駐車エリアで障害物が検出されました。周囲に障害物が存在するか確認してください。",
  "car.warnning.10015": "4号の安全レーダー警告2エリアがトリガーされました",
  "car.warnning.10016": "4号の安全レーダー警告1エリアがトリガーされました",
  "car.warnning.10017":
    "貨物搭載を要求していますが、NearEnd では貨物が検出されていません",
  "car.warnning.10018":
    "無貨を要求していますが、NearEnd で貨物が検出されています",
  "car.warnning.10019": "荷卸し完了ですが、NearEnd で貨物が検出されています",
  "car.warnning.10020":
    "積み込み完了ですが、NearEnd で貨物が検出されていません",
  "car.warnning.10021": "貨物を要求していますが、貨物が検出されていません",
  "car.warnning.10022": "無貨を要求していますが、貨物が検出されています",
  "car.warnning.10023":
    "荷物の取り扱い中、無貨を要求していますが、貨物が検出されています",
  "car.warnning.10024": "退出、無貨を要求していますが、貨物が検出されています",
  "car.warnning.10034":
    "BMS通信異常、自動充電ブラシ板と充電パイルの接触状況を確認してください",
  "car.warnning.10045": "TOFカメラ警告2エリアがトリガーされました",
  "car.warnning.10046": "TOFカメラ警告1エリアがトリガーされました",
  "car.warnning.10048": "レーザレーダ警告2エリアがトリガーされました",
  "car.warnning.10049": "レーザレーダ警告1エリアがトリガーされました",
  "car.warnning.10058": "スケジューリングシステム接続異常",
  "component.tagSelect.expand": "展開",
  "component.tagSelect.collapse": "格納",
  "component.globalHeader.search.example1": "検索ヒント1",
  "component.globalHeader.notification": "お知らせる",
  "component.globalHeader.notification.empty": "すべての通知を確認しました",
  "component.globalHeader.message.empty": "すべてのメッセージを読みました",
  "component.noticeIcon.clear": "クリア",
  "component.noticeIcon.cleared": "クリア済み",
  "component.noticeIcon.view-more": "もっと見る",
  "pager.name": "呼出し器名",
  "pager.name.s": "名前",
  "pager.type": "タイプ",
  "pager.detail.params.require.warn": "必須です",
  "senior.hmi.put_fetch-max_distance":
    "フロントバリアレーダ荷物取り放しモード最大距離",
  "senior.hmi.put_fetch-max_width":
    "フロントバリアレーダ荷物取り放しモード最大幅",
  "app.setting.content-width.fixed": "固定幅",
  "app.setting.content-width.fluid": "ストリーミング",
  "app.setting.themecolor.dust": "たそがれ",
  "app.setting.themecolor.sunset": "夕暮れ",
  "app.setting.themecolor.daybreak": "曙光ブルー（デフォルト）",
  "app.setting.themecolor.geekblue": "ギークブルー",
  "app.setting.themecolor.purple": "紫色",
  "app.settings.basic.email": "メールアドレス",
  "app.settings.basic.geographic-message": "都道府県を入力してください！",
  "app.settings.security.question-description":
    "秘密保護問題が設定されていません。秘密保護問題はアカウントの安全を確保するのに役立ちとます",
  "app.settings.security.email": "代替メールアドレス",
  "app.settings.security.email-description": "バインドされたメールアドレス",
  "app.settings.security.set": "設定",
  "app.settings.binding.taobao": "タオバオをバインドする",
  "app.settings.binding.alipay": "支付宝をバインドする",
  "app.settings.binding.alipay-description":
    "現在、アリペイのアカウントはバインドされていません",
  "app.settings.binding.dingding": "DingTalkをバインドする",
  "app.settings.binding.dingding-description":
    "現在DingTalkアカウントをバインドされていません",
  "app.settings.notification.password-description":
    "他のユーザーからのメッセージはサイト内メッセージとして通知されます",
  "app.settings.notification.messages-description":
    "システムメッセージはサイト内メッセージの形式で通知されます",
  "app.settings.notification.todo-description":
    "保留中のタスクはサイト内メッセージの形式で通知されます",
  "universal.search.button": "お問い合わせ",
  "universal.clear.value": "クリア",
  "universal.new.word": "追加",
  "universal.build.word": "作成",
  "universal.delete.word": "削除",
  "universal.sure.word": "确認",
  "universal.save.word": "保存",
  "universal.name.word": "名前",
  "universal.system.set.success": "設定が成功しました、自動的に更新されます",
  "universal.new.success.word": "追加成功",
  "universal.new.fail.word": "追加失敗",
  "universal.error.net": "要求異常",
};
